"""initial schema

Revision ID: 84463efe9adf
Revises: 
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '84463efe9adf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insights',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('severity', sa.String(length=16), server_default='info', nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('related_ticker', sa.String(length=24), nullable=True),
    sa.Column('related_sector', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=64), server_default='system', nullable=False),
    sa.Column('dismissed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_insight_owner', 'insights', ['user_id', 'market', 'dismissed'], unique=False)
    op.create_table('instruments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('ticker', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('sector', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'market', 'ticker', name='uq_instrument')
    )
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('captured_on', sa.Date(), nullable=False),
    sa.Column('total_invested', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('total_market_value', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('pnl_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('stock_count', sa.Integer(), nullable=False),
    sa.Column('sector_count', sa.Integer(), nullable=False),
    sa.Column('sector_allocations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'market', 'captured_on', name='uq_portfolio_day')
    )
    op.create_table('price_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('ticker', sa.String(length=24), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('market_cap', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('captured_on', sa.Date(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market', 'ticker', 'captured_on', name='uq_price_day')
    )
    op.create_table('transactions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('ticker', sa.String(length=24), nullable=False),
    sa.Column('txn_type', sa.String(length=8), nullable=False),
    sa.Column('units', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_txn_owner', 'transactions', ['user_id', 'market'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_txn_owner', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('price_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_table('instruments')
    op.drop_index('ix_insight_owner', table_name='insights')
    op.drop_table('insights')
    # ### end Alembic commands ###
